MedicalApp/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedicalApp.Controllers
{
    public class AdministrationController : Controller
    {
        // GET: Administration
        public ActionResult Index()
        {
            return View();
        }

        // GET: Administration/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Administration/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administration/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Administration/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Administration/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Administration/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Administration/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MedicalApp/Controllers/ReporterController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedicalApp.Models;
using MedicalApp.Models.dbOwnModels;
using ClosedXML;
using ClosedXML.Excel;
using System.IO;
using MedicalApp.Models.OwnModels;
using System.Text;
using System.Security.Cryptography;

namespace MedicalApp.Controllers
{
    public class ReporterController : Controller
    {
        Encryptor crypto = new Encryptor();
        // GET: Reporter
        public ActionResult Index()
        {
            try
            {
                ViewModel mymodel = new ViewModel();
                mymodel.PkUser = crypto.Encrypt(Session["PKUser"].ToString());
                return View(mymodel);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Login");
                throw;
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ExportData1(ViewModel vm)
        {
            string query = "";
            try
            {
                 query = "SELECT * FROM [MedicalApp].[dbo].[Tareas] where Asignado='" + crypto.Decrypt(vm.PkUser) + "' ";
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Login");
                throw;
            }

            String constring = ConfigurationManager.ConnectionStrings["MiConexionLocal"].ConnectionString;
            SqlConnection con = new SqlConnection(constring);
           
            DataTable dt = new DataTable();
            dt.TableName = "Tareas";
            con.Open();
            SqlDataAdapter da = new SqlDataAdapter(query, con);
            da.Fill(dt);
            con.Close();

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                wb.Style.Font.Bold = true;
                Response.Clear();
                Response.Buffer = true;
                Response.Charset = "";
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;filename= MisTareasAsignadas "+" "+ DateTime.Now+".xlsx");

                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.SaveAs(MyMemoryStream);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
            }
            return RedirectToAction("Index", "ExportData");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult XlsTareas2(ViewModel vm)
        {
            string query = "";
            try
            {
                query = "SELECT * FROM [MedicalApp].[dbo].[Tareas] where Asignador='" + crypto.Decrypt(vm.PkUser) + "' ";
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Login");
                throw;
            }

            String constring = ConfigurationManager.ConnectionStrings["MiConexionLocal"].ConnectionString;
            SqlConnection con = new SqlConnection(constring);

            DataTable dt = new DataTable();
            dt.TableName = "Tareas";
            con.Open();
            SqlDataAdapter da = new SqlDataAdapter(query, con);
            da.Fill(dt);
            con.Close();

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                wb.Style.Font.Bold = true;
                Response.Clear();
                Response.Buffer = true;
                Response.Charset = "";
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;filename= MisTareasAsignadas " + " " + DateTime.Now + ".xlsx");

                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.SaveAs(MyMemoryStream);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
            }
            return RedirectToAction("Index", "ExportData");
        }



        // GET: Reporter/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Reporter/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reporter/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reporter/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Reporter/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reporter/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reporter/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

MedicalApp/Views/Shared/_Layout.cshtml
@{

if (Session["FullUserName"] ==null)
{
    Response.Redirect("~/Login/Index");
}
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
    <link rel="icon" href="~/Content/Assets/images/tasklogo.png" type="image/gif" sizes="16x16">
    @Styles.Render("~/Content/css")
    @Scripts.Render(" ~/bundles/bootstrap")
   
    @*@Scripts.Render("~/bundles/modernizr")*@
  
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <link href="~/Content/Assets/FontAwesome/fontawesome/css/all.css" rel="stylesheet" />


    <style>
        .estilo515{
            color:#174270;
        }
        body {
            background-image: url('../../Content/Assets/images/doodles.png');
            background-size:25%;
        }
    </style>
</head>
<body style="background-color:#ffffff ">

   

    <nav class="navbar  navbar-expand-sm  navbar-dark" style="height:55px;background-color:#212121">


        <a href="@Url.Action("Index", "Home")" class="navbar-brand">
            

            <img src="~/Content/Assets/images/tasklogo.png"  style="max-height:42px" />
        </a>
       
        <ul class="navbar-nav">
            <li class="nav-item ">
                @Html.ActionLink("Inicio", "Index", "Home",null, new { @class = " estilo515 nav-link", @style = "color:#007bff" })
            </li>
            <li class="nav-item estilo515">
                @Html.ActionLink("Reportes", "Index", "Reporter", null, new { @class = "estilo515 nav-link", @style = "color:#007bff" })
            </li>

          
        </ul>
        <ul class="navbar-nav mr-auto"></ul>

        <ul class="navbar-nav">
            <li class="nav-item dropdown" style="margin-top:4px">
                
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" style="color:#007bff">
                   <label>@Session["FullUserName"].ToString().ToUpper()</label>
                    @Html.Hidden("lblUser", Session["User"].ToString())
                </a>
                <div class="dropdown-menu">
                    <a>
                        @Html.ActionLink("Administrador", "Index", "Administration", null, new { @class = "estilo515 dropdown-item" })
                    </a>
                    
                    <a>
                        @Html.ActionLink("Cerrar Sesion", "LogOut", "Login", null, new { @class = "dropdown-item" })
                       
                    </a>

                </div>
            </li>
        </ul>
    </nav>
    <br />
    <div class="container-fluid"  style="background-color: #fafafa; max-height: 54.5%; min-height: 54.5%; border: 1px solid  #9e9e9e; border-radius: 7px;max-width:1320px">
        @RenderBody()
       

        <br />
    </div>

    @RenderSection("scripts", required: false)

}


</body>
</html>